@startuml ユースケース図
left to right direction
actor 利用者 #DDDDDD;line:black;line.bold;
actor ホテル従業員 #DDDDDD;line:black;line.bold;
actor ホテル管理者 #DDDDDD;line:black;line.bold;
rectangle ホテル宿泊予約{
    usecase 空室状況を閲覧する
    usecase 予約する
    usecase 予約の集計をする
    usecase 空室状況を入力する
    usecase 会員登録する
    usecase ログインする
    usecase (<u>キャンペーン価格</u>\nキャンペーン期間中であればキャンペーン価格) as input
}
予約する.>ログインする :<<include>>
会員登録する <. ログインする
利用者 --> 空室状況を閲覧する
空室状況を入力する <-- ホテル従業員 
ホテル管理者 --> 予約の集計をする
(予約する)  <. input : <<extend>>
空室状況を入力する ..> ログインする : <<include>>
予約の集計をする ..> ログインする : <<include>>
利用者-->予約する
' ホテル管理者 --|>　ホテル従業員 
@enduml