@startuml ユースケース図
left to right direction
actor 利用者 #DDDDDD;line:black;line.bold;
rectangle ホテル宿泊予約{
    usecase ログインする
    usecase キャンペーン
    usecase (<u>予約する</u>\nキャンペーン期間中であればキャンペーン価格) as input
}
input.> ログインする:<<include>>
 (キャンペーン)   .>input : <<extend>>
利用者-->input
@enduml