@startuml 演習7-4-1_CL_ハンバーガーショップ_クラス図
class 注文明細{
    -合計:int
}
class 注文{
    -数量:int
    -小計:int
}
class 割引クーポン{
    -値引額:int
    -期限:int
}

class カップ{
    -サイズ:String
}

class ドリンク{
    -種別:String
}
class 商品{
    -名称:String
    -単価:int
}

class フード{
}
    

class ハンバーガー{
     -種別:String   
}

class 材料{
    
}
class レシピ{
   
}
class ポテト{
    -サイズ:String
}
class パン{

}
class 肉{

}
class 野菜{

}
class チーズ{
}

注文 "1.." o-ri- "*" 注文明細
注文明細 "0..*" -ri- "0..1" 割引クーポン
注文明細 "0..*" -down- "1" 商品
カップ "1..3" -ri- "0..*" ドリンク
ドリンク -ri-|> 商品
フード -up-|> 商品
フード "1" -ri- "1" レシピ
ハンバーガー -up-|> フード
ポテト -up-|> フード
材料 "1..*" -ri-o "1..*" ハンバーガー
パン -up-|> 材料
肉 -up-|> 材料
野菜 -up-|> 材料
チーズ -up-|> 材料

hide circle 
@enduml
