@startuml 演習6-5-1_クラス図_ライントレーサー
class ライントレーサー
class 光センサー
class 右モニター
class 左モニター
class CPU
class 電源SW

ライントレーサー "1"*--"1" 光センサー
ライントレーサー "1"*--"1"右モニター
ライントレーサー "1"*--"1" 左モニター
ライントレーサー "1"*--"1" CPU
ライントレーサー "1"*--"1"電源SW

@enduml