@startuml 演習6-3_ステートマシン図_診察予約システム.pu
left to right direction
[*] -right-> メニュー

state メニュー
state 予約と確認
state 貴方の順番 
state 今の順番


メニュー --> 予約と確認 : 予約を選択した場合
予約と確認 --> 貴方の順番   : 登録ボタンが押される
予約と確認 --> メニュー : キャンセルボタンが押される
予約と確認--> 貴方の順番 : 確認ボタンが押される
メニュー --> 今の順番 : 今の順番が押されたら
貴方の順番 --> メニュー : 戻るボタンが押される
今の順番 --> メニュー : 戻るボタンが押される

メニュー -right-> [*]

@enduml



